# Domefy Back-end server configuration file
#
#    Author: Aramis Hornung Moraes
#    Date: June 2019
#    
#
hosting_address = "localhost"
hosting_port = "9090"
system_version = "0.196.0.1"
win32_domefy_binary_cef = "..\\bin\\fpmed-with-cef.exe"
win32_domefy_binary = "..\\bin\\fpmed.exe"
gnulinux_domefy_binary = "../bin/fpmed"
selected_index_host_ip = 0