//
// FpMED - Framework for Distributed Multiprojection Systems
// Copyright Aramis Hornung Moraes 2014-2019
//

#ifndef FPMED_H
#define FPMED_H

#ifdef _WIN32
#include <windows.h>
#endif

#include <Core/CoreParameters.h>
#include <Core/FpmedCore.h>
#include <stdio.h>
#include <string.h>

//#include "Splash.h"

//#include "Urho3DAll.h"

// major, year+month, version, minor
#define fpmed_version "0.195.0.1"

#endif
